### ISSUE TITLE
Add a snippet to auto-complete "initialize" section

### ISSUE THREAD

**Issue by andrew-woosnam** [andrew-woosnam/impact-framework-vscode#6]
The "initialize" section of the manifest file has a predictable format. We should allow users to populate this section instantly when they start writing it out

```
initialize:
  plugins:
    <PLUGIN-NAME-HERE>: 
      method: 
      path: 
  outputs:
```
