### ISSUE TITLE
Add snippet to auto-complete "child" sections

### ISSUE THREAD

**Issue by andrew-woosnam** [andrew-woosnam/impact-framework-vscode#7]
When typing "child" nodes into a manifest file, provide an option to instantly populate this skeleton: 
```
child:
  pipeline:
  config:
  defaults:
  inputs:
    - timestamp: 
      duration: 
```
